#!/bin/sh
#
# PROVIDE: HugoMeet
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf to enable this service:
#
# HugoMeet_enable (bool): Set to NO by default.   
#
# Set it to YES to enable it.
 
. /etc/rc.subr
name="HugoMeet"
rcvar="${name}_enable"
load_rc_config $name
 
: ${mineos_enable:="NO"}
 
pidfile="/var/run/HugoMeet.pid"
command="/usr/local/bin/node"
 
start_precmd="export PATH=$PATH:/usr/local/bin"
command_args="/usr/local/www/setup.sh"
 
run_rc_command "$1"

